In [14]:
pip install scikit-learn category_encoders pandas numpy

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\USER\\PycharmProjects\\proj\\.venv\\Lib\\site-packages\\statsmodels\\sandbox\\distributions\\estimators.py'
Check the permissions.


[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting category_encoders
  Using cached category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\user\pycharmprojects\proj\.venv\lib\site-packages (from scikit-learn) (2.4.6)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: pandas>=1.0.5 in c:\users\user\pycharmprojects\proj\.venv\lib\site-packages (from category_encoders) (3.0.3)
Collecting patsy>=0.5.1 (from category_encoders)
  Using cached patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Collecting statsmodels>=0.9.0 (from category_encoders)
  Using cached statsmodels-0.14.6-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\pycharmprojects\proj\.venv\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\user\pycharmprojects\proj\.venv\lib\site-packages (from pandas>=1.0.5->category_encoders) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\user\pycharmprojects\proj\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: packaging>=21.3 in c:\users\user\pycharmprojects\proj\.venv\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (26.2)
Using cached scikit_learn-1.8.0-cp311-cp311-win_amd64.whl (8.1 MB)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Using cached scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
Using cached statsmodels-0.14.6-cp311-cp311-win_amd64.whl (9.6 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, patsy, joblib, scikit-learn, statsmodels, category_encoders

   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----- ---------------------------------- 1/7 [scipy]
   ----------- ---------------------------- 2/7 [patsy]
   ----------- ---------------------------- 2/7 [patsy]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [statsmodels]
   ---------------------------- ----------- 5/7 [statsmodels]
   ---------------------------- ----------- 5/7 [statsmodels]

Requirement already satisfied: scikit-learn in c:\users\user\pycharmprojects\proj\.venv\lib\site-packages (1.8.0)
Collecting category_encoders
  Using cached category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: pandas in c:\users\user\pycharmprojects\proj\.venv\lib\site-packages (3.0.3)
Requirement already satisfied: numpy in c:\users\user\pycharmprojects\proj\.venv\lib\site-packages (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in c:\users\user\pycharmprojects\proj\.venv\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\user\pycharmprojects\proj\.venv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\user\pycharmprojects\proj\.venv\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: patsy>=0.5.1 in c:\users\user\pycharmprojects\proj\.venv\lib\site-packages (from category_encoders) (1.0.2)
Collecting statsmodels>=0.9.0 (from category_encoders)
  Using cached statsmodels-0.14.6-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\pycharmprojects\proj\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\user\pycharmprojects\proj\.venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\user\pycharmprojects\proj\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: packaging>=21.3 in c:\users\user\pycharmprojects\proj\.venv\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (26.2)
Using cached category_encoders-2.9.0-py3-none-any.whl (85 kB)
Using cached statsmodels-0.14.6-cp311-cp311-win_amd64.whl (9.6 MB)
Installing collected packages: statsmodels, category_encoders

   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   ---------------------------------------- 0/2 [statsmodels]
   -------------------- ------------------- 1/2 [category_encoders]
   -------------------- ------------------- 1/2 [category_encoders]
   -------------------- ------------------- 1/2 [category_encoders]
   ---------------------------------------- 2/2 [category_encoders]

Successfully installed category_encoders-2.9.0 statsmodels-0.14.6
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from category_encoders import BinaryEncoder

In [16]:
raw_data_path= '../Data/Raw Data/'
clean_data_path= '../Data/Clean Data/'

In [17]:
raw_data_file=raw_data_path+'raw_data.csv'
df=pd.read_csv(raw_data_file)
df.head()

,TRANSACTION_NUMBER,INSTANCE_DATE,GROUP_EN,PROCEDURE_EN,IS_OFFPLAN_EN,IS_FREE_HOLD_EN,USAGE_EN,AREA_EN,PROP_TYPE_EN,PROP_SB_TYPE_EN,...,ACTUAL_AREA,ROOMS_EN,PARKING,NEAREST_METRO_EN,NEAREST_MALL_EN,NEAREST_LANDMARK_EN,TOTAL_BUYER,TOTAL_SELLER,MASTER_PROJECT_EN,PROJECT_EN
0,101-4-2026,2026-05-13 10:16:06,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,JUMEIRAH VILLAGE CIRCLE,Unit,Hotel Apartment,...,125.92,3 B/R,1,Dubai Internet City,Marina Mall,Sports City Swimming Academy,0,0,NaN,NORTH FORTY THREE SERVICED RESIDENCES
1,101-4-2026,2026-05-13 10:16:06,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,JUMEIRAH VILLAGE CIRCLE,Unit,Hotel Apartment,...,66.70,1 B/R,1,Dubai Internet City,Marina Mall,Sports City Swimming Academy,0,0,NaN,NORTH FORTY THREE SERVICED RESIDENCES
2,101-4-2026,2026-05-13 10:16:06,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,JUMEIRAH VILLAGE CIRCLE,Unit,Hotel Apartment,...,37.21,Studio,1,Dubai Internet City,Marina Mall,Sports City Swimming Academy,0,0,NaN,NORTH FORTY THREE SERVICED RESIDENCES
3,101-4-2026,2026-05-13 10:16:06,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,JUMEIRAH VILLAGE CIRCLE,Unit,Hotel Apartment,...,64.52,1 B/R,1,Dubai Internet City,Marina Mall,Sports City Swimming Academy,0,0,NaN,NORTH FORTY THREE SERVICED RESIDENCES
4,101-4-2026,2026-05-13 10:16:06,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,JUMEIRAH VILLAGE CIRCLE,Unit,Hotel Apartment,...,66.78,1 B/R,1,Dubai Internet City,Marina Mall,Sports City Swimming Academy,0,0,NaN,NORTH FORTY THREE SERVICED RESIDENCES

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27807 entries, 0 to 27806
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   TRANSACTION_NUMBER   27807 non-null  str
 1   INSTANCE_DATE        27807 non-null  str
 2   GROUP_EN             27807 non-null  str
 3   PROCEDURE_EN         27807 non-null  str
 4   IS_OFFPLAN_EN        27807 non-null  str
 5   IS_FREE_HOLD_EN      27807 non-null  str
 6   USAGE_EN             27807 non-null  str
 7   AREA_EN              27807 non-null  str
 8   PROP_TYPE_EN         27807 non-null  str
 9   PROP_SB_TYPE_EN      27475 non-null  str
 10  TRANS_VALUE          27807 non-null  float64
 11  PROCEDURE_AREA       27807 non-null  float64
 12  ACTUAL_AREA          27807 non-null  float64
 13  ROOMS_EN             24034 non-null  str
 14  PARKING              21944 non-null  str
 15  NEAREST_METRO_EN     12993 non-null  str
 16  NEAREST_MALL_EN      12739 non-null  str
 17  NEAREST_LANDMARK_EN  16606 non-null  str
 18  TOTAL_BUYER          27807 non-null  int64
 19  TOTAL_SELLER         27807 non-null  int64
 20  MASTER_PROJECT_EN    116 non-null    str
 21  PROJECT_EN           24361 non-null  str
dtypes: float64(3), int64(2), str(17)
memory usage: 4.7 MB

In [19]:
#Rename columns for easier navigation
column_names={
    'TRANSACTION_NUMBER':'transaction_num',
    'INSTANCE_DATE':'instance_date',
    'GROUP_EN':'group',
    'PROCEDURE_EN':'procedure',
    'IS_OFFPLAN_EN':'is_offplan',
    'IS_FREE_HOLD_EN':'is_free_hold',
    'USAGE_EN':'usage',
    'AREA_EN':'area',
    'PROP_TYPE_EN':'prop_type',
    'PROP_SB_TYPE_EN':'prop_sb_type',
    'TRANS_VALUE':'trans_value',
    'PROCEDURE_AREA':'procedure_area',
    'ACTUAL_AREA':'actual_area',
    'ROOMS_EN':'rooms',
    'PARKING':'parking',
    'NEAREST_METRO_EN':'nearest_metro',
    'NEAREST_MALL_EN':'nearest_mall',
    'NEAREST_LANDMARK_EN':'nearest_landmark',
    'TOTAL_BUYER':'total_buyer',
    'TOTAL_SELLER':'total_seller',
    'MASTER_PROJECT_EN':'master_project',
    'PROJECT_EN':'project'
}
df.rename(columns=column_names,inplace=True)
df

,transaction_num,instance_date,group,procedure,is_offplan,is_free_hold,usage,area,prop_type,prop_sb_type,...,actual_area,rooms,parking,nearest_metro,nearest_mall,nearest_landmark,total_buyer,total_seller,master_project,project
0,101-4-2026,2026-05-13 10:16:06,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,JUMEIRAH VILLAGE CIRCLE,Unit,Hotel Apartment,...,125.92,3 B/R,1,Dubai Internet City,Marina Mall,Sports City Swimming Academy,0,0,NaN,NORTH FORTY THREE SERVICED RESIDENCES
1,101-4-2026,2026-05-13 10:16:06,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,JUMEIRAH VILLAGE CIRCLE,Unit,Hotel Apartment,...,66.70,1 B/R,1,Dubai Internet City,Marina Mall,Sports City Swimming Academy,0,0,NaN,NORTH FORTY THREE SERVICED RESIDENCES
2,101-4-2026,2026-05-13 10:16:06,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,JUMEIRAH VILLAGE CIRCLE,Unit,Hotel Apartment,...,37.21,Studio,1,Dubai Internet City,Marina Mall,Sports City Swimming Academy,0,0,NaN,NORTH FORTY THREE SERVICED RESIDENCES
3,101-4-2026,2026-05-13 10:16:06,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,JUMEIRAH VILLAGE CIRCLE,Unit,Hotel Apartment,...,64.52,1 B/R,1,Dubai Internet City,Marina Mall,Sports City Swimming Academy,0,0,NaN,NORTH FORTY THREE SERVICED RESIDENCES
4,101-4-2026,2026-05-13 10:16:06,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,JUMEIRAH VILLAGE CIRCLE,Unit,Hotel Apartment,...,66.78,1 B/R,1,Dubai Internet City,Marina Mall,Sports City Swimming Academy,0,0,NaN,NORTH FORTY THREE SERVICED RESIDENCES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27802,95-69-2026,2026-04-02 15:13:36,Sales,Delayed Development,Ready,Non Free Hold,Residential,SILICON OASIS,Unit,Flat,...,110.01,1 B/R,B-29,NaN,NaN,IMG World Adventures,0,0,NaN,UNIESTATE MILLENNIUM TOWER
27803,95-70-2026,2026-04-23 20:07:22,Sales,Delayed Development,Ready,Non Free Hold,Residential,DUBAI INVESTMENT PARK SECOND,Unit,Flat,...,77.20,1 B/R,Building 15-2A-24,NaN,NaN,Expo 2020 Site,0,0,NaN,RITAJ
27804,95-71-2026,2026-05-02 11:05:53,Sales,Delayed Development,Ready,Non Free Hold,Residential,SILICON OASIS,Unit,Flat,...,48.55,Studio,P1-03,NaN,NaN,IMG World Adventures,0,0,NaN,UNIESTATE MILLENNIUM TOWER
27805,95-72-2026,2026-05-08 17:37:07,Sales,Delayed Development,Ready,Non Free Hold,Residential,DUBAI INVESTMENT PARK SECOND,Unit,Flat,...,76.99,1 B/R,15-3B-07,NaN,NaN,Expo 2020 Site,0,0,NaN,RITAJ
27806,95-73-2026,2026-05-08 17:35:34,Sales,Delayed Development,Ready,Non Free Hold,Residential,DUBAI INVESTMENT PARK SECOND,Unit,Flat,...,75.79,1 B/R,15-3B-08,NaN,NaN,Expo 2020 Site,0,0,NaN,RITAJ

In [20]:
#Check number of unique values in each column
print("Number of unique values in each column:")
for x in df.columns:
    print(f"{x}: {len(df[x].unique())}")
print("\n\n\nNumber of null values in each column:")
for x in df.columns:
    print(f"{x}: {df[x].isnull().sum()}")

Number of unique values in each column:
transaction_num: 26906
instance_date: 26522
group: 3
procedure: 31
is_offplan: 2
is_free_hold: 2
usage: 2
area: 232
prop_type: 3
prop_sb_type: 28
trans_value: 14049
procedure_area: 10981
actual_area: 10887
rooms: 13
parking: 3738
nearest_metro: 53
nearest_mall: 6
nearest_landmark: 14
total_buyer: 1
total_seller: 1
master_project: 8
project: 2318



Number of null values in each column:
transaction_num: 0
instance_date: 0
group: 0
procedure: 0
is_offplan: 0
is_free_hold: 0
usage: 0
area: 0
prop_type: 0
prop_sb_type: 332
trans_value: 0
procedure_area: 0
actual_area: 0
rooms: 3773
parking: 5863
nearest_metro: 14814
nearest_mall: 15068
nearest_landmark: 11201
total_buyer: 0
total_seller: 0
master_project: 27691
project: 3446

In [21]:
#Drop useless columns
df_original=df.copy()
df=df.drop(columns=['transaction_num','total_buyer','total_seller','master_project'])
df

,instance_date,group,procedure,is_offplan,is_free_hold,usage,area,prop_type,prop_sb_type,trans_value,procedure_area,actual_area,rooms,parking,nearest_metro,nearest_mall,nearest_landmark,project
0,2026-05-13 10:16:06,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,JUMEIRAH VILLAGE CIRCLE,Unit,Hotel Apartment,725538.46,125.92,125.92,3 B/R,1,Dubai Internet City,Marina Mall,Sports City Swimming Academy,NORTH FORTY THREE SERVICED RESIDENCES
1,2026-05-13 10:16:06,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,JUMEIRAH VILLAGE CIRCLE,Unit,Hotel Apartment,725538.46,66.70,66.70,1 B/R,1,Dubai Internet City,Marina Mall,Sports City Swimming Academy,NORTH FORTY THREE SERVICED RESIDENCES
2,2026-05-13 10:16:06,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,JUMEIRAH VILLAGE CIRCLE,Unit,Hotel Apartment,725538.46,37.21,37.21,Studio,1,Dubai Internet City,Marina Mall,Sports City Swimming Academy,NORTH FORTY THREE SERVICED RESIDENCES
3,2026-05-13 10:16:06,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,JUMEIRAH VILLAGE CIRCLE,Unit,Hotel Apartment,725538.46,64.52,64.52,1 B/R,1,Dubai Internet City,Marina Mall,Sports City Swimming Academy,NORTH FORTY THREE SERVICED RESIDENCES
4,2026-05-13 10:16:06,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,JUMEIRAH VILLAGE CIRCLE,Unit,Hotel Apartment,725538.46,66.78,66.78,1 B/R,1,Dubai Internet City,Marina Mall,Sports City Swimming Academy,NORTH FORTY THREE SERVICED RESIDENCES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27802,2026-04-02 15:13:36,Sales,Delayed Development,Ready,Non Free Hold,Residential,SILICON OASIS,Unit,Flat,1239213.00,110.01,110.01,1 B/R,B-29,NaN,NaN,IMG World Adventures,UNIESTATE MILLENNIUM TOWER
27803,2026-04-23 20:07:22,Sales,Delayed Development,Ready,Non Free Hold,Residential,DUBAI INVESTMENT PARK SECOND,Unit,Flat,640245.52,77.20,77.20,1 B/R,Building 15-2A-24,NaN,NaN,Expo 2020 Site,RITAJ
27804,2026-05-02 11:05:53,Sales,Delayed Development,Ready,Non Free Hold,Residential,SILICON OASIS,Unit,Flat,653238.00,48.55,48.55,Studio,P1-03,NaN,NaN,IMG World Adventures,UNIESTATE MILLENNIUM TOWER
27805,2026-05-08 17:37:07,Sales,Delayed Development,Ready,Non Free Hold,Residential,DUBAI INVESTMENT PARK SECOND,Unit,Flat,667701.03,76.99,76.99,1 B/R,15-3B-07,NaN,NaN,Expo 2020 Site,RITAJ
27806,2026-05-08 17:35:34,Sales,Delayed Development,Ready,Non Free Hold,Residential,DUBAI INVESTMENT PARK SECOND,Unit,Flat,652813.25,75.79,75.79,1 B/R,15-3B-08,NaN,NaN,Expo 2020 Site,RITAJ

In [22]:
# Fix and separate instance date
df['instance_date']=pd.to_datetime(df['instance_date'])

df['date_year']        = df['instance_date'].dt.year
df['date_month']       = df['instance_date'].dt.month
df['date_day']         = df['instance_date'].dt.day
df['date_hour']        = df['instance_date'].dt.hourg
df['date_day_of_week'] = df['instance_date'].dt.dayofweek
#Get rid of original column since its useless
df=df.drop(columns=['instance_date'])